sudo: required

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - wget

before_install:
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.4.0/bazel_0.4.0-linux-x86_64.deb'
  - sudo dpkg -i bazel_0.4.0-linux-x86_64.deb

script:
  - bazel build ...
  - bazel test ...
