dist: precise

sudo: required

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - gcc-5
      - g++-5

before_install:
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.4.4/bazel_0.4.4-linux-x86_64.deb'
  - chmod +x bazel_0.4.4-linux-x86_64.deb
  - sudo dpkg -i bazel_0.4.4-linux-x86_64.deb

script:
  - bazel build ...
  - bazel test ...
